### ISSUE TITLE
Problem with larger datasets - error releasing buffers

### ISSUE THREAD

**Issue by afterthought** [FasterXML/jackson-dataformat-protobuf#14]
Sorry I'm not able to provide a reproduction of this. I did debug through the code though and I'm pretty certain what is happening even though I'm not certain of the exact best fix.

I am creating objects that are over 10MB when encoded. I am hitting an exception in these cases, "Trying to release buffer not owned by the context". The error is thrown by IOContext.  What I traced down was that ProtobufGenerator in the constructor allocates _currBuffer using this code:

    _currBuffer = ctxt.allocWriteEncodingBuffer();

This allocates 8000 bytes. At some point during encoding (perhaps in _writeLengthPrefixed) the buffer is overwritten by calling:

    _currBuffer = ProtobufUtil.allocSecondary(_currBuffer);

This allocates 64000 bytes and now _currBuffer no longer points to the original buffer allocated using IOContext which is still retained by the IOContext class. When the encoding is done and the close method attempts to release the buffers, the verifyRelease function detects that the buffer retained by IOContext does not match the _currBuffer that later got allocated by the ProtobufGenerator.

        protected final void _verifyRelease(byte[] toRelease, byte[] src) {
            if(toRelease != src && toRelease.length <= src.length) {
                throw this.wrongBuf();
            }
        }

For the moment, I'm hacking in my own fix which just retains the originally allocated buffer to pass to releaseWriteEncodingBuffer when releasing. Let me know if this is a use-case you are interested in and want me to help test any proper fixes.

Thanks....

**Comment by cowtowncoder** [comment]
Thank you for reporting this @afterthought. If you get that exception there certainly is a problem of some kind. It would be nice to have a reproduction, but these kind of issues are often tricky to have tests for.
It is quite possible that check could be too strict; I think one other dataformat module had some similar issues, but can't remember exactly which. Problem was that the sanity check was not taking into account possibility of resize, which does change the identity of buffer, like here.

**Comment by afterthought** [comment]
Once I get through my short-term deliverables, I'll see if I can get a test together.

**Comment by cowtowncoder** [comment]
Test would be great if you have time.

Looking at code I see what you mean, and also remember the logic of the test. Obviously doesn't work here unfortunately. Need to see what is the easiest fix here, given that `IOContext` comes from `jackson-core`.

**Comment by cowtowncoder** [comment]
I am able to reproduce the problem; needed to use a nested POJO along with large enough content.
Should be easy enough to verify the fix.

**Comment by cowtowncoder** [comment]
Should be fixed now, will be in 2.7.3. Will fix in `jackson-core` for 2.8, but work-around should be fine for now.

**Comment by afterthought** [comment]
Awesome. Thanks!
