### ISSUE TITLE
Will this library support Descriptor?

### ISSUE THREAD

**Issue by isaiah** [FasterXML/jackson-dataformat-protobuf#6]
This will be a very useful library. But I have a question, why it parses `.proto` file instead of take existing `Descriptor`? It's kind of reinventing the wheel here. If it accepts `Descriptor` it can also support the reflection API. 

I am talking about the approach used by [protobuf-java-format](https://code.google.com/p/protobuf-java-format/) library.

**Comment by cowtowncoder** [comment]
What `Descriptor` are you thinking of? And how would that fit in the picture? Proto files are the standard external definitions of protobuf schemas, but I am open to other sources if they make sense.
However, proto definition coupled with matching beans seem like a reasonable source. But as with Avro and CSV format modules, it is possible to add proto schema generation as well.

I also do not understand why this would be reinventing the wheel. Project is using `protoparser` (https://github.com/square/protoparser) project for parsing proto into internal definition.

**Comment by isaiah** [comment]
For `Descriptor` I mean the thingie that represents the schema. e.g.

```java
Descriptor descriptor = MyProtobufMessage.newBuilder().getDescriptorForType();
```
the `descriptor` will contain everything you need.

For a typical java program the user deals with `Descriptor`. It's reinventing the wheel because `protoc` already turns the `.proto` file into `Descriptor`s.

The `protobuf-java-format` lib is very cool, it does `serialize/deserialize` to different formats besides `json`, and it event used `jackson-smile`, however it seems unmaintained.

**Comment by HiJon89** [comment]
I think the point is to be able to serialize/deserialize POJOs using the protobuf wire format, so there wouldn't be a descriptor

**Comment by HiJon89** [comment]
If you already have protobuf objects and just want Jackson support to write/read them as JSON you can out [this](https://github.com/HubSpot/jackson-datatype-protobuf) library, which is maintained (by me :))

**Comment by cowtowncoder** [comment]
@isaiah Right, I guessed it would describe some aspects, but I wanted to know which actual class (that is, from which library) it comes from. I don't want to add dependencies to other protobuf decoder libraries, but if this was something from JDK it might work.

But as I said, ability to also construct schemas programmatically makes sense even though I expect that the common/majority use case is in fact use of proto definitions externally: most likely this extension is used to also allow protobuf encoding as an alternative, and not as much for cases where it is the only (or primary) format.

So: any improvements to allow construction of `ProtobufSchema` without having to give actual proto definition would be welcome. One such source should be Jackson's own introspection capability. 
https://github.com/FasterXML/jackson-dataformat-avro has means to do this (for example), as does CSV module (https://github.com/FasterXML/jackson-dataformat-csv).

I still do not understand the claim for reinventing the wheel: your explanation does not help there unfortunately. I am also not convinced that not using proto files (or equivalent input) is a common Java usage. It just seems like plenty of work, error-prone, and problematic for interoperability.

@HiJon89 Yes, good point; that library allows use of protoc-generated objects, for producing other outputs.

**Comment by cowtowncoder** [comment]
Ok. Reading through `protobuf-java-format`, I see `Descriptor` would come from core protobuf lif.

So I think there is misunderstanding: this project is not designed to take protobuf `Message` objects; rather, @HiJon89 pointed out a library that does. So that will make sense.
From this, `Descriptor` is not something we would use here.

Instead, this dataformat library is a replacement for the lower-level protobuf encoder/decoder, to be used with regular POJOs, or `Map`s, `List`s and so on.

**Comment by isaiah** [comment]
Thank you all for the time, I'll check out @HiJon89 's lib.
