### ISSUE TITLE
Add a way to programmatically construct `ProtobufSchema` instances without proto file

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-protobuf#7]
Currently the only way to construct a schema needed for decoding and encoding is to use a `proto` file (or String).
While is the common way of defining and using schemas, it would be useful to be alternatively able to construct schemas programmatically. This would allow use of alternate sources.

Another possibility (for which different issue may be filed) is to build schemas out of general Jackson introspection functionality.

**Comment by os72** [comment]
It is possible to construct protobuf schemas programmatically, but the API is a bit obscure. I'm putting together DynamicSchema to make it easier:
https://github.com/os72/protobuf-dynamic

I could also see this in combination with protoparser as front-end...

**Comment by cowtowncoder** [comment]
Ah. That sounds like it would work really nicely here. Thank you for the link -- I'll need to have a closer look when I get a chance. I like the idea of separate library which can be used by other projects as well.
And if I get far enough, this could also allow generation of protoc definitions via Jackson introspection, starting with POJOs or perhaps even JSON Schema, at some point.

**Comment by cowtowncoder** [comment]
Looking at the package, I am actually not sure whether it helps here. It adds dependency to `protobuf-java` which I'd rather not included, and uses its abstractions. In fact, library looks like a thin wrapper around protobuf-java really. But it is still good to see an example of usage, maybe it can give ideas at least, even if not implementation.

**Comment by os72** [comment]
Yes it's an ease-of-use wrapper, as small as possible. protobuf-java supports all that, it's just confusing to use with all those "descriptor" flavors. I guess you're looking to encode/decode protobuf content without using protobuf-java?

**Comment by cowtowncoder** [comment]
Module already encodes and decodes without use of `protobuf-java`, and parsing is done by Square's small `protoparser` library so right, none of `protobuf-java` abstractions is currently used.
Thank you for pointing to the library still, it is good to see how problem is approached.

I'll still need to see if `protoparser` representation would work or not; and if it does, whether to change dependency to regular one from shaded (shading is for private dependencies, not good if exposing types). Also need to find balance between what to expose; some of the feature of full protobuf implementation do not seem very useful, and/or are difficult to map to usual POJO databinding.

**Comment by cowtowncoder** [comment]
Recreated as https://github.com/FasterXML/jackson-dataformats-binary/issues/4 as part of consolidation
